### ISSUE TITLE
Use URLcrypt from controller

### ISSUE THREAD

**Issue by Carpela** [cheerful/URLcrypt#5]
I might be being dumb here, but for some reason I'm getting an error trying to use URLcrypt inside a controller? 

    query = URLcrypt.decode params[:q]

any reason why this should give me a 

     uninitialized constant ThingController::URLcrypt

**Comment by jwilsjustin** [comment]
Do you have an initializer file?

Try creating a `urlcrypt.rb` file in the `/config/initializers` directory with something like:

```ruby
URLcrypt::key = ['longhexkeygoeshere'].pack('H*')
```

**Comment by jwilsjustin** [comment]
Or maybe you need to `require` the right module

```ruby
require 'URLcrypt'
``` 

As indicated from this PR: #4

**Comment by Carpela** [comment]
Seem to have it working. If I'm honest I couldn't tell you quite what I did. 
Only issue I have now is that I get a warning:
vendor/bundle/gems/urlcrypt-0.1.1/lib/URLcrypt.rb:7: warning: already initialized constant URLcrypt::TABLE
So I'm loading it twice somewhere. Works a treat though.
